LeaveManagementSystem/Models/ErrorViewModel.cs
namespace LeaveManagementSystem.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

LeaveManagementSystem/Models/LeaveTypes/IndexVM.cs
using System.ComponentModel.DataAnnotations;

namespace LeaveManagementSystem.Models.LeaveTypes
{
    public class IndexVM
    {
        public int LeaveTypeId { get; set; }

        [Required]
        [Length(4,150, ErrorMessage = "Leave Type Name must be between 4 and 150 characters.")]
        public string LeaveTypeName { get; set; }= string.Empty;

        [Required]
        [Range(1,90)]
        public int Days { get; set; }
    }
}

LeaveManagementSystem/Models/TestViewModel.cs
namespace LeaveManagementSystem.Models
{
    public class TestViewModel
    {
        public string Name { get; set; }
        public DateTime? DateofBirth { get; set; }
    }
}

LeaveManagementSystem/Controllers/HomeController.cs
using System.Diagnostics;
using LeaveManagementSystem.Models;
using Microsoft.AspNetCore.Mvc;

namespace LeaveManagementSystem.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

     


        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

LeaveManagementSystem/Controllers/LeaveTypesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using LeaveManagementSystem.Data;

namespace LeaveManagementSystem.Controllers
{
    public class LeaveTypesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public LeaveTypesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: LeaveTypes
        public async Task<IActionResult> Index()
        {
            //var data=SELECT * FROM LeaveTypes
            var data = await _context.LeaveTypes.ToListAsync();
            //convert datamodel to view model
            var viewData = data.Select(x => new Models.LeaveTypes.IndexVM
            {
                LeaveTypeId = x.LeaveTypeId,
                LeaveTypeName = x.LeaveTypeName,
                Days = x.NumberOfDays
            });
            // return view model to view  
            return View(viewData);
        }

        // GET: LeaveTypes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var leaveType = await _context.LeaveTypes
                .FirstOrDefaultAsync(m => m.LeaveTypeId == id);
            if (leaveType == null)
            {
                return NotFound();
            }

            return View(leaveType);
        }

        // GET: LeaveTypes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: LeaveTypes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("LeaveTypeId,LeaveTypeName,NumberOfDays")] LeaveType leaveType)
        {
            //if(leaveType.LeaveTypeName.Contains("Vacation"))
            //{                
            //    ModelState.AddModelError("LeaveTypeName", "Vacation is not allowed in leave type name");
            //}
            if(await CheckIfLeaveTypeNameExists(leaveType.LeaveTypeName))
            {
                ModelState.AddModelError(nameof(leaveType.LeaveTypeName), "This Leave Type already exists in the database");
            }
            if (ModelState.IsValid)
            {
                _context.Add(leaveType);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(leaveType);
        }
         private async Task<bool> CheckIfLeaveTypeNameExists(string name)
        {
            var lowercaseName = name.ToLower();
            return await _context.LeaveTypes.AnyAsync(q => q.LeaveTypeName.ToLower().Equals(lowercaseName));
        }
        // GET: LeaveTypes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var leaveType = await _context.LeaveTypes.FindAsync(id);
            if (leaveType == null)
            {
                return NotFound();
            }
            return View(leaveType);
        }

        // POST: LeaveTypes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("LeaveTypeId,LeaveTypeName,NumberOfDays")] LeaveType leaveType)
        {
            if (id != leaveType.LeaveTypeId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(leaveType);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!LeaveTypeExists(leaveType.LeaveTypeId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(leaveType);
        }

        // GET: LeaveTypes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var leaveType = await _context.LeaveTypes
                .FirstOrDefaultAsync(m => m.LeaveTypeId == id);
            if (leaveType == null)
            {
                return NotFound();
            }

            return View(leaveType);
        }

        // POST: LeaveTypes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var leaveType = await _context.LeaveTypes.FindAsync(id);
            if (leaveType != null)
            {
                _context.LeaveTypes.Remove(leaveType);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool LeaveTypeExists(int id)
        {
            return _context.LeaveTypes.Any(e => e.LeaveTypeId == id);
        }
    }
}

LeaveManagementSystem/Controllers/TestController.cs
using LeaveManagementSystem.Models;
using Microsoft.AspNetCore.Mvc;

namespace LeaveManagementSystem.Controllers
{
    public class TestController : Controller
    {
        public IActionResult Index()
        {
            var data = new TestViewModel
            {
                Name = "Student of MVC COURSE",
                DateofBirth=new DateTime(1997,08,19)
            };
            return View(data);
        }
    }
}

LeaveManagementSystem/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

LeaveManagementSystem/Views/LeaveTypes/Create.cshtml
@model LeaveManagementSystem.Data.LeaveType

@{
    ViewData["Title"] = "Create";
}

<h1>Create Leave Type </h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="LeaveTypeName" class="control-label"></label>
                <input asp-for="LeaveTypeName" class="form-control" />
                <span asp-validation-for="LeaveTypeName" class="text-danger"></span>
            </div>
            <br/>
            <div class="form-group">
                <label asp-for="NumberOfDays" class="control-label"></label>
                <input asp-for="NumberOfDays" class="form-control" />
                <span asp-validation-for="NumberOfDays" class="text-danger"></span>
            </div>
            <br/>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-success" />
                <a asp-action="Index" class="btn btn-primary">Back to List</a>

            </div>
        </form>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

LeaveManagementSystem/Views/LeaveTypes/Delete.cshtml
@model LeaveManagementSystem.Data.LeaveType

@{
    ViewData["Title"] = "Delete Leave Type";
}

<h1>Delete Leave Type</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LeaveTypeName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LeaveTypeName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NumberOfDays)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NumberOfDays)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="LeaveTypeId" />
        <input type="submit" value="Delete" class="btn btn-danger" />
        <a asp-action="Index" class="btn btn-primary">Back to List</a>
    </form>
</div>

LeaveManagementSystem/Views/LeaveTypes/Details.cshtml
@model LeaveManagementSystem.Data.LeaveType

@{
    ViewData["Title"] =$"{Model.LeaveTypeName} Details";
}

<h1>Leave Type Details of @Model.LeaveTypeName</h1>

<div>
    </hr>
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LeaveTypeName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LeaveTypeName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NumberOfDays)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NumberOfDays)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" class="btn btn-warning" asp-route-id="@Model?.LeaveTypeId">Edit</a> |
    <a asp-action="Index" class="btn btn-primary">Back to List</a>
</div>

LeaveManagementSystem/Views/LeaveTypes/Edit.cshtml
@model LeaveManagementSystem.Data.LeaveType

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit LeaveType</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="LeaveTypeId" />
            <div class="form-group">
                <label asp-for="LeaveTypeName" class="control-label"></label>
                <input asp-for="LeaveTypeName" class="form-control" />
                <span asp-validation-for="LeaveTypeName" class="text-danger"></span>
            </div>
            <br/>
            <div class="form-group">
                <label asp-for="NumberOfDays" class="control-label"></label>
                <input asp-for="NumberOfDays" class="form-control" />
                <span asp-validation-for="NumberOfDays" class="text-danger"></span>
            </div>
            <br/>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-warning" />
                <a asp-action="Index" class="btn btn-primary">Back to List</a>
            </div>
        </form>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

LeaveManagementSystem/Views/LeaveTypes/Index.cshtml
@using LeaveManagementSystem.Models.LeaveTypes;
@model IEnumerable<IndexVM>
@{
    ViewData["Title" ] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create" class="btn btn-primary">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.LeaveTypeName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Days)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.LeaveTypeName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Days)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.LeaveTypeId" class="btn btn-warning">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.LeaveTypeId" class="btn btn-info">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.LeaveTypeId" class="btn btn-danger">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

LeaveManagementSystem/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - LeaveManagementSystem</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/LeaveManagementSystem.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">LeaveManagementSystem</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="LeaveTypes" asp-action="Index">Leave Types</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted bg-dark">
        <div class="container">
            &copy; 2026 - LeaveManagementSystem - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

LeaveManagementSystem/Views/Test/Index.cshtml
@model TestViewModel

@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Test View";
}
<h1>Hello from Test Controller</h1>
<h2>Your name is: @Model.Name</h2>

@if(Model.DateofBirth.HasValue)
{
    <h2>Your DOB is: @Model.DateofBirth</h2>
}